// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAQmV1Iue6jFdDd-WpLCelKaFFZgaBMYM',
    appId: '1:383562891006:web:5e6b47513d00dcc984afaf',
    messagingSenderId: '383562891006',
    projectId: 'wander-lust-17d91',
    authDomain: 'wander-lust-17d91.firebaseapp.com',
    storageBucket: 'wander-lust-17d91.firebasestorage.app',
    measurementId: 'G-094X9N683B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_u7MQ1ebxw1Ix0G-QXbn8-pQ9CAtDUMQ',
    appId: '1:383562891006:android:f9cc2bd725fc828d84afaf',
    messagingSenderId: '383562891006',
    projectId: 'wander-lust-17d91',
    storageBucket: 'wander-lust-17d91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzxchl-1DF23OYfacS5EVbmDfpZuAw6OA',
    appId: '1:383562891006:ios:e31f26994dadbe5f84afaf',
    messagingSenderId: '383562891006',
    projectId: 'wander-lust-17d91',
    storageBucket: 'wander-lust-17d91.firebasestorage.app',
    iosBundleId: 'com.example.wanderlust',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzxchl-1DF23OYfacS5EVbmDfpZuAw6OA',
    appId: '1:383562891006:ios:e31f26994dadbe5f84afaf',
    messagingSenderId: '383562891006',
    projectId: 'wander-lust-17d91',
    storageBucket: 'wander-lust-17d91.firebasestorage.app',
    iosBundleId: 'com.example.wanderlust',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAQmV1Iue6jFdDd-WpLCelKaFFZgaBMYM',
    appId: '1:383562891006:web:6af950e62d7398ec84afaf',
    messagingSenderId: '383562891006',
    projectId: 'wander-lust-17d91',
    authDomain: 'wander-lust-17d91.firebaseapp.com',
    storageBucket: 'wander-lust-17d91.firebasestorage.app',
    measurementId: 'G-N8W3VHM2Y4',
  );
}
